name: IOT DEVICE ANDROID DEBUG CI

on:
  push:
    paths-ignore:
      - '**/doc*/**'
      - '**/**/doc*/**'
      - '**/README.md'
      - '**/LICENSE'
      - '*.md'
      - '**/*.md'
    tags-ignore:
      - '*'
    branches:
      - '*'
  pull_request:
    branches: [ master ]

env:
  IOT_SONATYPE_USERNAME: ${{ secrets.IOT_SONATYPE_USERNAME }}
  IOT_SONATYPE_PASSWORD: ${{ secrets.IOT_SONATYPE_PASSWORD }}
  GPG_DECRYPT_PASSPHRASE: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          rm -rf hub/hub-android-demo/src/main/assets/app-config.json explorer/device-android-demo/src/main/assets/app-config.json hub/hub-device-java/src/test/resources/unit_test_config.json explorer/explorer-device-java/src/test/resources/unit_test_config.json
          gpg -d --passphrase "$GPG_DECRYPT_PASSPHRASE" --batch --quiet .github/hub-device-android/app-config.json.asc > hub/hub-android-demo/src/main/assets/app-config.json
          gpg -d --passphrase "$GPG_DECRYPT_PASSPHRASE" --batch --quiet .github/explorer-device-android/app-config.json.asc > explorer/device-android-demo/src/main/assets/app-config.json
          gpg -d --passphrase "$GPG_DECRYPT_PASSPHRASE" --batch --quiet .github/hub-device-java/unit_test_config.json.asc > hub/hub-device-java/src/test/resources/unit_test_config.json
          gpg -d --passphrase "$GPG_DECRYPT_PASSPHRASE" --batch --quiet .github/explorer-device-java/unit_test_config.json.asc > explorer/explorer-device-java/src/test/resources/unit_test_config.json
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: install fir
        run: sudo gem install fir-cli
      - name: Update SdkDemo Version
        run: |
          rb=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          rc=$(git rev-parse --short HEAD)
          sed -i "s#xxx#$rb+git.$rc#g" config.gradle
      - name: Setup NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;22.0.7026061"
      - name: Update SDK Version
        run: bash .github/scripts/updateVersionCodeForSnapshot.sh
      - name: Test with Gradle
        run: ./gradlew test --info
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Publish aar and jar to Maven
        run: ./gradlew publish
      - name: Archive the apks
        uses: actions/upload-artifact@v2
        with:
          path: |
            'explorer/device-android-demo/build/outputs/apk/debug/*.apk'
            'hub/hub-android-demo/build/outputs/apk/debug/*.apk'
      - name: Upload apks to fir
        run: |
          expApk=$(ls explorer/device-android-demo/build/outputs/apk/debug/*.apk)
          hubApk=$(ls hub/hub-android-demo/build/outputs/apk/debug/*.apk)

          rc=$(git rev-parse --short HEAD)
          rl=$(git log --pretty=format:"%s" $rc -1)
          fir publish $expApk -T $IOT_FIRIM_API_TOKEN -c "$rl" --oversea_turbo --force_pin_history -V
          fir publish $hubApk -T $IOT_FIRIM_API_TOKEN -c "$rl" --oversea_turbo --force_pin_history -V
        env:
          IOT_FIRIM_API_TOKEN: ${{ secrets.IOT_FIRIM_API_TOKEN }}
